agents:
  - name: openai-default
    kind: python
    cmd: python scripts/agents/openai_agent.py --task {task_dir} --tests {test_file} --cache {run_root}/cache --repair-once

  - name: copyref
    kind: python
    cmd: python scripts/agents/copy_ref_agent.py --task {task_dir} --ref {orig_task_dir}
