name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run benchmarks (Python + JS if present)
        run: |
          python runner/vibebench_runner.py --tasks tasks/python --out results.json --csv results.csv --metrics configs/metrics.v1.json
          python scripts/analyze_results.py || true
          # JS optional:
          node -v >/dev/null 2>&1 && node runner/vibebench_runner_js.mjs || true

      - name: Package artifacts
        run: |
          mkdir -p dist
          zip -rq dist/vibebench-results.zip results.json results.csv scorecard.md reports || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/vibebench-results.zip
            results.json
            results.csv
            scorecard.md
            reports/summary.md
            reports/agents_costs.md
            reports/agents_costs.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}